/**
 * Channel Types - Message Normalization Layer
 *
 * Defines standardized message formats for multi-channel communication.
 * All channel adapters normalize their input/output into these formats,
 * enabling the agent service to remain channel-agnostic.
 */

import type { ThinkingEffort } from '../utils/openai-models'

// ============================================
// Normalized Attachments
// ============================================

export type NormalizedAttachment =
  | { type: 'image'; id: string; mediaType: string; data: string; name?: string; size?: number }
  | { type: 'pdf'; id: string; mediaType: 'application/pdf'; data: string; name: string; size: number }
  | { type: 'text'; id: string; mediaType: string; content: string; name: string; size: number; language?: string }

// ============================================
// Inbound Message (User → Agent)
// ============================================

/**
 * Channel-agnostic inbound message.
 * All channel adapters normalize their input into this format.
 */
export interface NormalizedInboundMessage {
  /** Unique message ID (generated by channel adapter) */
  id: string
  /** Channel identifier: 'electron' | 'remote-web' | 'telegram' | ... */
  channelId: string
  /** Channel-specific client identifier (for response routing) */
  clientId: string
  /** Target space and conversation */
  spaceId: string
  conversationId: string
  /** Core message content */
  text: string
  /** Runtime-only prefix injected before text (not persisted) */
  textPrefix?: string
  /** Resume an existing session */
  resumeSessionId?: string
  /** Attachments (images, PDFs, text files) */
  attachments?: NormalizedAttachment[]
  /** Model configuration */
  model?: {
    name?: string
    source?: string
    thinkingEffort?: ThinkingEffort
  }
  /** Feature toggles */
  features?: {
    aiBrowser?: boolean
  }
  /** Channel-specific metadata (opaque to core, passed through) */
  channelMeta?: Record<string, unknown>
  /** Timestamp (ms since epoch) */
  timestamp: number
}

// ============================================
// Outbound Events (Agent → User)
// ============================================

export type OutboundEventType =
  | 'agent:start'
  | 'agent:message'
  | 'agent:thought'
  | 'agent:tool-call'
  | 'agent:tool-result'
  | 'agent:tool-approval-resolved'
  | 'agent:complete'
  | 'agent:error'
  | 'agent:compact'
  | 'agent:queued'
  | 'agent:status'
  | 'agent:user-question'
  | 'agent:user-question-answered'
  | 'agent:task-update'
  | 'agent:subagent-update'
  | 'agent:host-step'
  | 'agent:mcp-status'

/**
 * Standardized outbound event envelope.
 * The agent service emits these; the ChannelManager routes them to the right channels.
 */
export interface NormalizedOutboundEvent {
  /** Event type */
  type: OutboundEventType
  /** Target identifiers */
  spaceId: string
  conversationId: string
  /** Event payload (type-specific, flat object for backward compatibility) */
  payload: Record<string, unknown>
  /** Timestamp (ms since epoch) */
  timestamp: number
}
